weights: polygon-yolov5s-ucas.pt
cfg: ./models/polygon_yolov5s_ucas.yaml
data: ./data/polygon_ucas.yaml
hyp: ./data/hyp.ucas.yaml
epochs: 10
batch_size: 4
img_size:
- 1024
- 1024
rect: false
resume: false
nosave: false
notest: false
noautoanchor: true
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: cpu
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
polygon: true
world_size: 1
global_rank: -1
save_dir: runs/train/exp2
total_batch_size: 4
